<?php

?>
<div id="tabs-acl-tabs">
<div class="easyui-tabs" id="tab" style="width:930px;height:auto;">
    <div title="General" id="tab_acl" iconCls="icon-acl">
          <iframe id="general_acl" src="<?php echo $GLOBALS['webroot']; ?>/interface/modules/zend_modules/public/acl/acl?module_id=<?php echo $this->escapeHtml($this->mod_id); ?>" style="width:100%;height: 700px;overflow: hidden;" frameborder="0"></iframe>
    </div>
    <div title="Advanced ACL" id="tab_acl2" iconCls="icon-acladvanced">
          <iframe id="advanced_acl" src="<?php echo $GLOBALS['webroot']; ?>/interface/modules/zend_modules/public/acl/index?module_id=<?php echo $this->escapeHtml($this->mod_id); ?>" style="width:100%;height: 700px;overflow: hidden;" frameborder="0"></iframe>
    </div>
</div>
</div>
